/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 810e85d5737f64470b3aed0ea133fb29)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		ARK_API_KEY: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		GUIDE_AUDIO_BUCKET: R2Bucket;
		AI: Ai;
	}
}

interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ARK_API_KEY">> {
		QDRANT_URL: string;
        OPENAI_EMBEDDING_API_KEY: string;
        GOOGLE_MAPS_API_KEY: string;
	}
}
